theme: jekyll-theme-minimal

title: "mulle-core"
description: "C libraries based on mulle-c and mulle-concurrent"
logo: 'https://avatars1.githubusercontent.com/u/44543973?s=256'
show_downloads: false


highlighter: rouge

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

